---
- name: prometheus configuration with Ansible
  gather_facts: true
  hosts: Redhartservers
  become: true

  tasks:
    - name: create prometheus user
      user:
        name: prometheus
        append: true
        shell: /usr/bin/nologin
        system: true
        create_home: false
    
    - name: create prmometheus dir
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
        group: prometheus
      loop:
        - /etc/promethus
        - /var/lib/prometheus

    - name: download prometheus
      get_url:
        url: https://github.com/prometheus/prometheus/releases/download/v2.22.0/prometheus-2.22.0.linux-amd64.tar.gz
        dest: /tmp/
        mode: 0755
        owner: prometheus
        group: prometheus

    - name: Unarchive prometheus-2.22.0.linux-amd64.tar.gz
      unarchive:
        src: /tmp/prometheus-2.22.0.linux-amd64.tar.gz
        dest: /tmp/
        remote_src: yes
    
    - name: Copy prometheus and promtool binary
      copy:
        src:
        dest: "/usr/local/bin/"
        owner: prometheus
        group: prometheus
        mode: 0755
        remote_src: yes
      loop:
        - /tmp/prometheus-2.22.0.linux-amd64/prometheus
        - /tmp/prometheus-2.22.0.linux-amd64/promtool